Repository US-EPA-CAMD/easey-qa-certification-api, pull requests merged in 2022-11, with the labels that each got.

#249 chore: update easey-common
  package.json
  yarn.lock
Labels: Emissioners

#250 fix rata-26
  src/dto/rata-run.dto.ts
Labels: Emissioners

#251 Feature/4113: QA & Cert: RATA Traverse DTO Checks
  src/dto/flow-rata-run.dto.ts
  src/dto/rata-traverse.dto.ts
  src/entities/rata-traverse.entity.ts
  src/entities/workspace/pressure-measure-code.entity.ts
  src/entities/workspace/rata-traverse.entity.ts
  src/maps/rata-traverse.map.ts
  src/rata-traverse-workspace/rata-traverse-workspace.service.ts
Labels: Emissioners

#255 Feature/3978 rata test qualifications checks
  src/dto/test-qualification.dto.ts
  src/test-qualification-workspace/test-qualification-checks.service.ts
  src/test-qualification-workspace/test-qualification-workspace.controller.ts
  src/test-qualification-workspace/test-qualification-workspace.module.ts
Labels: Emissioners

#256 fix: rata-74 check
  src/dto/rata-traverse.dto.ts
Labels: Emissioners

#257 add exportFuelFlowToLoadBaseline
  src/fuel-flow-to-load-baseline-workspace/fuel-flow-to-load-baseline-workspace.service.ts
  src/fuel-flow-to-load-baseline/fuel-flow-to-load-baseline.service.ts
  src/test-summary-workspace/test-summary.service.ts
  src/test-summary/test-summary.module.ts
  src/test-summary/test-summary.service.ts
Labels: Emissioners

#253 Fix Bug to Save Monitor System ID in Test Summary
  src/entities/monitor-system.entity.ts
  src/entities/test-summary.entity.ts
  src/entities/workspace/test-summary.entity.ts
  src/test-summary-workspace/test-summary.service.spec.ts
  src/test-summary-workspace/test-summary.service.ts
Labels: Emissioners

#254 Add Online Offline Calibration to OFFICIAL export
  src/online-offline-calibration-workspace/online-offline-calibration.service.spec.ts
  src/online-offline-calibration/online-offline-calibration.service.spec.ts
  src/online-offline-calibration/online-offline-calibration.service.ts
  src/test-summary/test-summary.module.ts
  src/test-summary/test-summary.service.spec.ts
  src/test-summary/test-summary.service.ts
Labels: Emissioners

#258 ✨Feature/4114: QA & Cert: RATA Traverse DTO Checks
  src/dto/rata-traverse.dto.ts
  src/flow-rata-run-workspace/flow-rata-run-checks.service.ts
  src/qa-certification-workspace/qa-certification-checks.service.ts
  src/rata-traverse-workspace/rata-traverse-checks.service.spec.ts
  src/rata-traverse-workspace/rata-traverse-checks.service.ts
  src/rata-traverse-workspace/rata-traverse-workspace.module.ts
Labels: Emissioners

#259 add checks to POST testQualification
  src/test-qualification-workspace/test-qualification-workspace.controller.ts
Labels: Emissioners

#260 fix: RATA-77-B check
  src/dto/rata-traverse.dto.ts
Labels: Emissioners

#261 rata-test-qualification-checks
  src/entities/workspace/test-qualification.entity.ts
  src/test-qualification-workspace/test-qualification-checks.service.ts
  src/test-qualification-workspace/test-qualification-workspace.repository.ts
  src/test-qualification-workspace/test-qualification-workspace.service.ts
Labels: Emissioners

#262 fix import online-offline-calibration
  src/online-offline-calibration-workspace/online-offline-calibration.service.ts
Labels: Emissioners

#263 code cleanup
  src/test-summary-workspace/test-summary.service.ts
Labels: Emissioners

#265 code cleanup
  src/test-qualification-workspace/test-qualification-checks.service.ts
  src/test-qualification-workspace/test-qualification-workspace.service.ts
Labels: Emissioners

#266 Unit Tests: Increase Unit Test Coverage
  src/analyzer-range-workspace/analyzer-range.module.ts
  src/analyzer-range-workspace/analyzer-range.repository.spec.ts
  src/analyzer-range-workspace/analyzer-range.service.spec.ts
  src/analyzer-range-workspace/analyzer-range.service.ts
  src/rata-summary-workspace/rata-summary-check.service.spec.ts
  src/test-qualification-workspace/test-qualification-workspace.controller.spec.ts
Labels: Emissioners

#267 fix export bug
  src/test-summary/test-summary.service.ts
Labels: Emissioners

#270 ✨ Feature/2934-2935: API Endpoint - Add & View Cycle Time Summary Data
  src/analyzer-range-workspace/analyzer-range.repository.spec.ts
  src/app.module.ts
  src/calibration-injection-workspace/calibration-injection-workspace.controller.spec.ts
  src/calibration-injection-workspace/calibration-injection-workspace.service.spec.ts
  src/cycle-time-summary-workspace/cycle-time-summary-workspace.controller.spec.ts
  src/cycle-time-summary-workspace/cycle-time-summary-workspace.controller.ts
  src/cycle-time-summary-workspace/cycle-time-summary-workspace.module.ts
  src/cycle-time-summary-workspace/cycle-time-summary-workspace.repository.ts
  src/cycle-time-summary-workspace/cycle-time-summary-workspace.service.spec.ts
  src/cycle-time-summary-workspace/cycle-time-summary-workspace.service.ts
  src/cycle-time-summary/cycle-time-summary.controller.spec.ts
  src/cycle-time-summary/cycle-time-summary.controller.ts
  src/cycle-time-summary/cycle-time-summary.module.ts
  src/cycle-time-summary/cycle-time-summary.repository.ts
  src/cycle-time-summary/cycle-time-summary.service.spec.ts
  src/cycle-time-summary/cycle-time-summary.service.ts
  src/dto/cycle-time-summary.dto.ts
  src/dto/flow-rata-run.dto.ts
  src/entities/cycle-time-summary.entity.ts
  src/entities/test-summary.entity.ts
  src/entities/workspace/cycle-time-summary.entity.ts
  src/entities/workspace/test-summary.entity.ts
  src/maps/cycle-time-summary.map.spec.ts
  src/maps/cycle-time-summary.map.ts
  src/maps/test-summary.map.ts
  src/routes.ts
  src/test-summary-workspace/test-summary-checks.service.spec.ts
  src/test-summary-workspace/test-summary.module.ts
  src/test-summary/test-summary.module.ts
Labels: Emissioners

#271 ✨ Feature/3078-3079: API Endpoint - EDIT & DELETE Cycle Time Summary
  src/cycle-time-summary-workspace/cycle-time-summary-workspace.controller.spec.ts
  src/cycle-time-summary-workspace/cycle-time-summary-workspace.controller.ts
  src/cycle-time-summary-workspace/cycle-time-summary-workspace.service.spec.ts
  src/cycle-time-summary-workspace/cycle-time-summary-workspace.service.ts
  src/cycle-time-summary/cycle-time-summary.controller.spec.ts
Labels: Emissioners

#273 ✨ Feature/2938-3077: Cycle Time Summary Import and Export for Workspace and Official
  src/cycle-time-summary-workspace/cycle-time-summary-workspace.module.ts
  src/cycle-time-summary-workspace/cycle-time-summary-workspace.service.spec.ts
  src/cycle-time-summary-workspace/cycle-time-summary-workspace.service.ts
  src/cycle-time-summary/cycle-time-summary.service.spec.ts
  src/cycle-time-summary/cycle-time-summary.service.ts
  src/test-summary-workspace/test-summary.service.spec.ts
  src/test-summary-workspace/test-summary.service.ts
  src/test-summary/test-summary.service.spec.ts
  src/test-summary/test-summary.service.ts
Labels: Emissioners

#276 add rata 118,119,120 checks
  src/dto/test-qualification.dto.ts
  src/test-qualification-workspace/test-qualification-checks.service.ts
Labels: Emissioners

#280 Feature/4144 rata traverse checks
  src/dto/rata-traverse.dto.ts
  src/rata-traverse-workspace/rata-traverse-checks.service.ts
  src/test-qualification-workspace/test-qualification-checks.service.ts
Labels: Emissioners

#281 feature/3036 Add CREATE TransmitterTransducerAccuracy API Endpoint
  src/app.module.ts
  src/dto/test-summary.dto.ts
  src/dto/transmitter-transducer-accuracy.dto.ts
  src/dto/transmitter-transducer.dto.ts
  src/entities/test-summary.entity.ts
  src/entities/workspace/test-summary.entity.ts
  src/entities/workspace/transmitter-transducer-accuracy.entity.ts
  src/maps/test-summary.map.ts
  src/maps/transmitter-transducer-accuracy.map.ts
  src/routes.ts
  src/test-summary-workspace/test-summary.service.ts
  src/test-summary/test-summary.service.ts
  src/transmitter-transducer-accuracy-workspace/transmitter-transducer-accuracy.controller.spec.ts
  src/transmitter-transducer-accuracy-workspace/transmitter-transducer-accuracy.controller.ts
  src/transmitter-transducer-accuracy-workspace/transmitter-transducer-accuracy.module.ts
  src/transmitter-transducer-accuracy-workspace/transmitter-transducer-accuracy.repository.ts
  src/transmitter-transducer-accuracy-workspace/transmitter-transducer-accuracy.service.spec.ts
  src/transmitter-transducer-accuracy-workspace/transmitter-transducer-accuracy.service.ts
Labels: Emissioners

#284 Revert "feature/3036 Add CREATE TransmitterTransducerAccuracy API Endpoint"
  src/app.module.ts
  src/dto/test-summary.dto.ts
  src/dto/transmitter-transducer-accuracy.dto.ts
  src/dto/transmitter-transducer.dto.ts
  src/entities/test-summary.entity.ts
  src/entities/workspace/test-summary.entity.ts
  src/entities/workspace/transmitter-transducer-accuracy.entity.ts
  src/maps/test-summary.map.ts
  src/maps/transmitter-transducer-accuracy.map.ts
  src/routes.ts
  src/test-summary-workspace/test-summary.service.ts
  src/test-summary/test-summary.service.ts
  src/transmitter-transducer-accuracy-workspace/transmitter-transducer-accuracy.controller.spec.ts
  src/transmitter-transducer-accuracy-workspace/transmitter-transducer-accuracy.controller.ts
  src/transmitter-transducer-accuracy-workspace/transmitter-transducer-accuracy.module.ts
  src/transmitter-transducer-accuracy-workspace/transmitter-transducer-accuracy.repository.ts
  src/transmitter-transducer-accuracy-workspace/transmitter-transducer-accuracy.service.spec.ts
  src/transmitter-transducer-accuracy-workspace/transmitter-transducer-accuracy.service.ts
Labels: Emissioners

#283 refactor and fix rata test qualification checks
  src/fuel-flowmeter-accuracy-workspace/fuel-flowmeter-accuracy-workspace.repository.spec.ts
  src/fuel-flowmeter-accuracy/fuel-flowmeter-accuracy.repository.spec.ts
  src/qa-certification-workspace/qa-certification-checks.service.spec.ts
  src/qa-certification-workspace/qa-certification-checks.service.ts
  src/qa-certification-workspace/qa-certification.module.ts
  src/rata-traverse-workspace/rata-traverse-checks.service.spec.ts
  src/rata-traverse-workspace/rata-traverse-workspace.controller.spec.ts
  src/rata-traverse-workspace/rata-traverse-workspace.controller.ts
  src/test-qualification-workspace/test-qualification-checks.service.ts
  src/test-qualification-workspace/test-qualification-workspace.controller.ts
  src/test-summary-workspace/test-summary-checks.service.spec.ts
  src/test-summary-workspace/test-summary.service.spec.ts
Labels: Emissioners

#287 Feature/4439 add cycle time injection data
  src/app.module.ts
  src/cycle-time-injection-workspace/cycle-time-injection-workspace.controller.spec.ts
  src/cycle-time-injection-workspace/cycle-time-injection-workspace.controller.ts
  src/cycle-time-injection-workspace/cycle-time-injection-workspace.module.ts
  src/cycle-time-injection-workspace/cycle-time-injection-workspace.repository.ts
  src/cycle-time-injection-workspace/cycle-time-injection-workspace.service.spec.ts
  src/cycle-time-injection-workspace/cycle-time-injection-workspace.service.ts
  src/cycle-time-injection/cycle-time-injection.controller.spec.ts
  src/cycle-time-injection/cycle-time-injection.controller.ts
  src/cycle-time-injection/cycle-time-injection.module.ts
  src/cycle-time-injection/cycle-time-injection.repository.ts
  src/cycle-time-injection/cycle-time-injection.service.spec.ts
  src/cycle-time-injection/cycle-time-injection.service.ts
  src/cycle-time-summary-workspace/cycle-time-summary-workspace.module.ts
  src/cycle-time-summary/cycle-time-summary.module.ts
  src/dto/cycle-time-injection.dto.ts
  src/dto/cycle-time-summary.dto.ts
  src/dto/linearity-summary.dto.ts
  src/entities/cycle-time-injection.entity.ts
  src/entities/cycle-time-summary.entity.ts
  src/entities/workspace/cycle-time-injection.entity.ts
  src/entities/workspace/cycle-time-summary.entity.ts
  src/linearity-injection-workspace/linearity-injection.controller.spec.ts
  src/maps/cycle-time-injection.map.spec.ts
  src/maps/cycle-time-injection.map.ts
  src/maps/cycle-time-summary.map.spec.ts
  src/maps/cycle-time-summary.map.ts
  src/routes.ts
Labels: Emissioners

#288 Feature/3036, 3035 - CREATE, VIEW Transmitter Transducer Accuracy API Endpoints
  src/app.module.ts
  src/cycle-time-injection/cycle-time-injection.controller.spec.ts
  src/dto/test-summary.dto.ts
  src/dto/transmitter-transducer-accuracy.dto.ts
  src/dto/transmitter-transducer.dto.ts
  src/entities/test-summary.entity.ts
  src/entities/transmitter-transducer-accuracy.entity.ts
  src/entities/workspace/test-summary.entity.ts
  src/entities/workspace/transmitter-transducer-accuracy.entity.ts
  src/maps/transmitter-transducer-accuracy.map.ts
  src/rata-traverse-workspace/rata-traverse-checks.service.ts
  src/routes.ts
  src/transmitter-transducer-accuracy-workspace/transmitter-transducer-accuracy.controller.spec.ts
  src/transmitter-transducer-accuracy-workspace/transmitter-transducer-accuracy.controller.ts
  src/transmitter-transducer-accuracy-workspace/transmitter-transducer-accuracy.module.ts
  src/transmitter-transducer-accuracy-workspace/transmitter-transducer-accuracy.repository.ts
  src/transmitter-transducer-accuracy-workspace/transmitter-transducer-accuracy.service.spec.ts
  src/transmitter-transducer-accuracy-workspace/transmitter-transducer-accuracy.service.ts
  src/transmitter-transducer-accuracy/transmitter-transducer-accuracy.controller.spec.ts
  src/transmitter-transducer-accuracy/transmitter-transducer-accuracy.controller.ts
  src/transmitter-transducer-accuracy/transmitter-transducer-accuracy.module.ts
  src/transmitter-transducer-accuracy/transmitter-transducer-accuracy.repository.ts
  src/transmitter-transducer-accuracy/transmitter-transducer-accuracy.service.spec.ts
  src/transmitter-transducer-accuracy/transmitter-transducer-accuracy.service.ts
Labels: Emissioners

#290 add deleteTranmitterTransducerAccuracy
  src/cycle-time-summary-workspace/cycle-time-summary-workspace.service.spec.ts
  src/transmitter-transducer-accuracy-workspace/transmitter-transducer-accuracy.controller.spec.ts
  src/transmitter-transducer-accuracy-workspace/transmitter-transducer-accuracy.controller.ts
  src/transmitter-transducer-accuracy-workspace/transmitter-transducer-accuracy.service.spec.ts
  src/transmitter-transducer-accuracy-workspace/transmitter-transducer-accuracy.service.ts
Labels: Emissioners

#293 setup test-qualication-checks-service unit-tests
  src/dto/monitor-system.dto.ts
  src/test-qualification-workspace/test-qualification-checks.service.spec.ts
Labels: Testing

#294 fix failing tests
  src/maps/cycle-time-injection.map.spec.ts
  src/test-summary-workspace/test-summary-checks.service.spec.ts
Labels: Testing

#295 Review & Submit Test Summary
  src/app.module.ts
  src/dto/review-and-submit-multiple-params.dto.ts
  src/dto/review-and-submit-test-summary.dto.ts
  src/entities/test-summary-review-and-submit.entity.ts
  src/maps/review-and-submit-test-summary.map.ts
  src/review-and-submit/review-and-submit-test-summary.controller.spec.ts
  src/review-and-submit/review-and-submit-test-summary.repository.ts
  src/review-and-submit/review-and-submit-test-summary.service.spec.ts
  src/review-and-submit/review-and-submit.controller.ts
  src/review-and-submit/review-and-submit.module.ts
  src/review-and-submit/review-and-submit.service.ts
  src/routes.ts
Labels: Tech Team

#297 fix issue wiht numberOfLoadLevels being undefined
  src/test-qualification-workspace/test-qualification-checks.service.ts
Labels: Emissioners

#299 fix: rata-79 not firing error issue
  src/rata-traverse-workspace/rata-traverse-checks.service.ts
Labels: Emissioners
