Repository US-EPA-CAMD/easey-qa-certification-api, pull requests merged in 2023-01, with the labels that each got.

#335 ✨ Feature/3105: API Endpoint - Edit Unit Default Test Run Data
  src/dto/unit-default-test-run.dto.ts
  src/entities/unit-default-test-run.entity.ts
  src/entities/unit-default-test.entity.ts
  src/entities/workspace/unit-default-test-run.entity.ts
  src/entities/workspace/unit-default-test.entity.ts
  src/maps/unit-default-test-run.map.ts
  src/routes.ts
  src/test-summary/test-summary.service.ts
  src/unit-default-test-run-workspace/unit-default-test-run.controller.spec.ts
  src/unit-default-test-run-workspace/unit-default-test-run.controller.ts
  src/unit-default-test-run-workspace/unit-default-test-run.module.ts
  src/unit-default-test-run-workspace/unit-default-test-run.repository.ts
  src/unit-default-test-run-workspace/unit-default-test-run.service.spec.ts
  src/unit-default-test-run-workspace/unit-default-test-run.service.ts
  src/unit-default-test-run/unit-default-test-run.controller.spec.ts
  src/unit-default-test-run/unit-default-test-run.controller.ts
  src/unit-default-test-run/unit-default-test-run.repository.ts
  src/unit-default-test-run/unit-default-test-run.service.spec.ts
  src/unit-default-test-run/unit-default-test-run.service.ts
  src/unit-default-test-workspace/unit-default-test-workspace.controller.spec.ts
  src/unit-default-test-workspace/unit-default-test-workspace.controller.ts
  src/unit-default-test-workspace/unit-default-test-workspace.service.spec.ts
  src/unit-default-test-workspace/unit-default-test-workspace.service.ts
  src/unit-default-test/unit-default-test.controller.spec.ts
  src/unit-default-test/unit-default-test.controller.ts
  src/unit-default-test/unit-default-test.service.spec.ts
  src/unit-default-test/unit-default-test.service.ts
Labels: Emissioners

#336 ✨ Feature/4460: Add Unit Default Test Run data elements to Export Endpoint
  src/unit-default-test-run-workspace/unit-default-test-run.service.spec.ts
  src/unit-default-test-run-workspace/unit-default-test-run.service.ts
  src/unit-default-test-run/unit-default-test-run.service.spec.ts
  src/unit-default-test-run/unit-default-test-run.service.ts
  src/unit-default-test-workspace/unit-default-test-workspace.module.ts
  src/unit-default-test-workspace/unit-default-test-workspace.service.spec.ts
  src/unit-default-test-workspace/unit-default-test-workspace.service.ts
  src/unit-default-test/unit-default-test.module.ts
  src/unit-default-test/unit-default-test.service.spec.ts
  src/unit-default-test/unit-default-test.service.ts
Labels: Emissioners

#338 🐛 Bug/4600: Test Summary Modal displaying a minute feild error
  src/dto/test-summary.dto.ts
  src/utilities/constants.ts
Labels: Emissioners

#339 🐛 Bug/4600: Test Summary Modal displaying a minute feild error
  src/test-summary-workspace/test-summary-checks.service.ts
Labels: Emissioners

#341 add IMPORT unit-default-test-run
  src/unit-default-test-run-workspace/unit-default-test-run.service.spec.ts
  src/unit-default-test-run-workspace/unit-default-test-run.service.ts
  src/unit-default-test-workspace/unit-default-test-workspace.service.spec.ts
  src/unit-default-test-workspace/unit-default-test-workspace.service.ts
Labels: Emissioners

#342 fix import unit-default-test run bug
  src/unit-default-test-run-workspace/unit-default-test-run.module.ts
Labels: bug

#347 4210 - Refactor Check Result Messages for Test Summary Checks
  src/test-summary-workspace/test-summary-checks.service.ts
Labels: Emissioners

#348 ✨ Feature/3059: API Endpoint - Add QA Test Extensions Exemptions Data
  src/app.module.ts
  src/dto/test-extension-exemption.dto.ts
  src/entities/test-extension-exemption.entity.ts
  src/entities/test-summary.entity.ts
  src/entities/workspace/test-extension-exemption.entity.ts
  src/entities/workspace/test-summary.entity.ts
  src/maps/test-extension-exemption.map.spec.ts
  src/maps/test-extension-exemption.map.ts
  src/qa-certification/qa-certification.service.spec.ts
  src/routes.ts
  src/test-extension-exemptions-workspace/test-extension-exemptions-workspace.controller.spec.ts
  src/test-extension-exemptions-workspace/test-extension-exemptions-workspace.controller.ts
  src/test-extension-exemptions-workspace/test-extension-exemptions-workspace.module.ts
  src/test-extension-exemptions-workspace/test-extension-exemptions-workspace.repository.spec.ts
  src/test-extension-exemptions-workspace/test-extension-exemptions-workspace.repository.ts
  src/test-extension-exemptions-workspace/test-extension-exemptions-workspace.service.spec.ts
  src/test-extension-exemptions-workspace/test-extension-exemptions-workspace.service.ts
  src/test-summary-workspace/test-summary.service.spec.ts
  src/test-summary-workspace/test-summary.service.ts
  src/utilities/test-extension-exemption.querybuilder.ts
Labels: Emissioners

#352 fix/Class-Validate
  package.json
Labels: Tech Team

#357 add DELETE qa-cert-event and unit tests
  src/dto/qa-certification-event.dto.ts
  src/qa-certification-event-workshop/qa-certification-event-workshop.controller.spec.ts
  src/qa-certification-event-workshop/qa-certification-event-workshop.controller.ts
  src/qa-certification-event-workshop/qa-certification-event-workshop.service.spec.ts
  src/qa-certification-event-workshop/qa-certification-event-workshop.service.ts
Labels: Emissioners

#359 Feature/774 edit test ext exempt data
  src/test-extension-exemptions-workspace/test-extension-exemptions-workspace.controller.spec.ts
  src/test-extension-exemptions-workspace/test-extension-exemptions-workspace.controller.ts
  src/test-extension-exemptions-workspace/test-extension-exemptions-workspace.service.spec.ts
  src/test-extension-exemptions-workspace/test-extension-exemptions-workspace.service.ts
  src/test-summary-workspace/test-summary-checks.service.ts
  src/test-summary-workspace/test-summary.service.spec.ts
  src/test-summary-workspace/test-summary.service.ts
Labels: Emissioners

#360 ✨ Feature/771: Add QA Cert Events Data elements to Export Endpoint
  package.json
  src/air-emission-testing-workspace/air-emission-testing-workspace.controller.spec.ts
  src/app-e-correlation-test-run-workspace/app-e-correlation-test-run-workspace.controller.spec.ts
  src/app-e-correlation-test-summary-workspace/app-e-correlation-test-summary-workspace.controller.spec.ts
  src/app-e-heat-input-from-oil-workspace/app-e-heat-input-from-oil.controller.spec.ts
  src/calibration-injection-workspace/calibration-injection-workspace.controller.spec.ts
  src/cycle-time-injection-workspace/cycle-time-injection-workspace.controller.spec.ts
  src/cycle-time-summary-workspace/cycle-time-summary-workspace.controller.spec.ts
  src/dto/qa-certification-params.dto.ts
  src/flow-rata-run-workspace/flow-rata-run-workspace.controller.spec.ts
  src/flow-to-load-check-workspace/flow-to-load-check-workspace.controller.spec.ts
  src/flow-to-load-check/flow-to-load-check.controller.spec.ts
  src/flow-to-load-reference-workspace/flow-to-load-reference-workspace.controller.spec.ts
  src/fuel-flow-to-load-baseline-workspace/fuel-flow-to-load-baseline-workspace.controller.spec.ts
  src/fuel-flow-to-load-test-workspace/fuel-flow-to-load-test-workspace.controller.spec.ts
  src/fuel-flowmeter-accuracy-workspace/fuel-flowmeter-accuracy-workspace.controller.spec.ts
  src/hg-injection-workspace/hg-injection-workspace.controller.spec.ts
  src/hg-injection/hg-injection.controller.spec.ts
  src/hg-summary-workspace/hg-summary-workspace.controller.spec.ts
  src/hg-summary/hg-summary.controller.spec.ts
  src/linearity-injection-workspace/linearity-injection.controller.spec.ts
  src/linearity-summary-workspace/linearity-summary.controller.spec.ts
  src/online-offline-calibration-workspace/online-offline-calibration.controller.spec.ts
  src/protocol-gas-workspace/protocol-gas.controller.spec.ts
  src/qa-certification-event-workshop/qa-certification-event-workshop.controller.spec.ts
  src/qa-certification-event-workshop/qa-certification-event-workshop.controller.ts
  src/qa-certification-event-workshop/qa-certification-event-workshop.repository.spec.ts
  src/qa-certification-event-workshop/qa-certification-event-workshop.repository.ts
  src/qa-certification-event-workshop/qa-certification-event-workshop.service.spec.ts
  src/qa-certification-event-workshop/qa-certification-event-workshop.service.ts
  src/qa-certification-event/qa-certification-event.controller.spec.ts
  src/qa-certification-event/qa-certification-event.controller.ts
  src/qa-certification-event/qa-certification-event.repository.spec.ts
  src/qa-certification-event/qa-certification-event.repository.ts
  src/qa-certification-event/qa-certification-event.service.spec.ts
  src/qa-certification-event/qa-certification-event.service.ts
  src/qa-certification-workspace/qa-certification.controller.spec.ts
  src/qa-certification-workspace/qa-certification.module.ts
  src/qa-certification-workspace/qa-certification.service.spec.ts
  src/qa-certification-workspace/qa-certification.service.ts
  src/qa-certification/qa-certification.module.ts
  src/qa-certification/qa-certification.service.spec.ts
  src/qa-certification/qa-certification.service.ts
  src/rata-run-workspace/rata-run-workspace.controller.spec.ts
  src/rata-summary-workspace/rata-summary-workspace.controller.spec.ts
  src/rata-workspace/rata-workspace.controller.spec.ts
  src/test-extension-exemptions-workspace/test-extension-exemptions-workspace.controller.spec.ts
  src/test-extension-exemptions/test-extension-exemptions.controller.spec.ts
  src/test-qualification-workspace/test-qualification-workspace.controller.spec.ts
  src/test-summary-workspace/test-summary.controller.spec.ts
  src/transmitter-transducer-accuracy-workspace/transmitter-transducer-accuracy.controller.spec.ts
  src/unit-default-test-run-workspace/unit-default-test-run.controller.spec.ts
  src/unit-default-test-run/unit-default-test-run.controller.spec.ts
  src/unit-default-test-workspace/unit-default-test-workspace.controller.spec.ts
  src/unit-default-test/unit-default-test.controller.spec.ts
  src/utilities/qa-cert-events.querybuilder.ts
  yarn.lock
Labels: Emissioners

#366 Feature/767 edit qa cert event
  src/dto/qa-certification-params.dto.ts
  src/entities/qa-certification-event.entity.ts
  src/entities/workspace/qa-certification-event.entity.ts
  src/maps/qa-certification-event.map.spec.ts
  src/maps/qa-certification-event.map.ts
  src/qa-certification-event-workshop/qa-certification-event-workshop.controller.ts
  src/qa-certification-event-workshop/qa-certification-event-workshop.repository.spec.ts
  src/qa-certification-event-workshop/qa-certification-event-workshop.repository.ts
  src/qa-certification-event-workshop/qa-certification-event-workshop.service.spec.ts
  src/qa-certification-event-workshop/qa-certification-event-workshop.service.ts
  src/qa-certification-event/qa-certification-event.repository.spec.ts
  src/qa-certification-event/qa-certification-event.repository.ts
  src/qa-certification-event/qa-certification-event.service.spec.ts
  src/qa-certification-event/qa-certification-event.service.ts
  src/utilities/qa-cert-events.querybuilder.ts
Labels: Emissioners

#365 ✨ Feature/766: Add QA Cert Events Data elements to Import Endpoint and 🐛 Bug/4668: Return 3-digit monitoringSystemID and componentRecordID
  src/app.module.ts
  src/dto/certification-event.dto.ts
  src/dto/qa-certification.dto.ts
  src/entities/qa-certification-event.entity.ts
  src/entities/workspace/qa-certification-event.entity.ts
  src/maps/qa-certification-event.map.spec.ts
  src/maps/qa-certification-event.map.ts
  src/qa-certification-event-workspace/qa-certification-event-workspace.controller.spec.ts
  src/qa-certification-event-workspace/qa-certification-event-workspace.controller.ts
  src/qa-certification-event-workspace/qa-certification-event-workspace.module.ts
  src/qa-certification-event-workspace/qa-certification-event-workspace.repository.spec.ts
  src/qa-certification-event-workspace/qa-certification-event-workspace.repository.ts
  src/qa-certification-event-workspace/qa-certification-event-workspace.service.spec.ts
  src/qa-certification-event-workspace/qa-certification-event-workspace.service.ts
  src/qa-certification-event/qa-certification-event.controller.spec.ts
  src/qa-certification-event/qa-certification-event.repository.spec.ts
  src/qa-certification-event/qa-certification-event.repository.ts
  src/qa-certification-event/qa-certification-event.service.spec.ts
  src/qa-certification-event/qa-certification-event.service.ts
  src/qa-certification-workspace/qa-certification.module.ts
  src/qa-certification-workspace/qa-certification.service.spec.ts
  src/qa-certification-workspace/qa-certification.service.ts
  src/qa-certification/qa-certification.service.spec.ts
  src/routes.ts
  src/utilities/qa-cert-events.querybuilder.ts
Labels: Emissioners

#364 Feature/4666 qa check extexem 8
  src/qa-certification-workspace/qa-certification-checks.service.spec.ts
  src/qa-certification-workspace/qa-certification-checks.service.ts
  src/qa-certification-workspace/qa-certification.module.ts
  src/test-extension-exemptions-workspace/test-extension-exemptions-checks.service.spec.ts
  src/test-extension-exemptions-workspace/test-extension-exemptions-checks.service.ts
  src/test-extension-exemptions-workspace/test-extension-exemptions-workspace.controller.spec.ts
  src/test-extension-exemptions-workspace/test-extension-exemptions-workspace.controller.ts
  src/test-extension-exemptions-workspace/test-extension-exemptions-workspace.module.ts
Labels: Emissioners

#371 Bug fix: checks
  src/qa-certification-workspace/qa-certification-checks.service.ts
Labels: Emissioners

#374 add linear-10 cases
  src/dto/test-summary.dto.ts
Labels: Emissioners

#373 ✨Feature/4650: QA Checks - Duplicate Records
  src/dto/test-summary.dto.ts
  src/qa-certification-workspace/qa-certification-checks.service.spec.ts
  src/qa-certification-workspace/qa-certification-checks.service.ts
  src/qa-certification-workspace/qa-certification.module.ts
  src/qa-certification-workspace/qa-certification.service.ts
  src/qa-certification/qa-certification.module.ts
  src/test-extension-exemptions-workspace/test-extension-exemptions-checks.service.spec.ts
  src/test-extension-exemptions-workspace/test-extension-exemptions-workspace.controller.spec.ts
  src/test-summary-workspace/test-summary-checks.service.spec.ts
  src/test-summary-workspace/test-summary-checks.service.ts
  src/utilities/constants.ts
Labels: Emissioners

#375 Feature/4651 qa checks dto validations
  src/dto/protocol-gas.dto.ts
  src/entities/workspace/gas-type-code.entity.ts
  src/enums/gas-type-code.enum.ts
  src/protocol-gas-workspace/protocol-gas-checks.service.spec.ts
  src/protocol-gas-workspace/protocol-gas-checks.service.ts
  src/protocol-gas-workspace/protocol-gas.module.ts
  yarn.lock
Labels: Emissioners

#378 Feature/review submit latest
  src/app.module.ts
  src/dto/cert-event-review-and-submit.dto.ts
  src/dto/tee-review-and-submit.dto.ts
  src/entities/workspace/cert-event-review-and-submit.entity.ts
  src/entities/workspace/tee-review-and-submit.entity.ts
  src/entities/workspace/test-summary-review-and-submit.entity.ts
  src/maps/cert-event-review-and-submit.map.ts
  src/maps/review-and-submit-test-summary.map.ts
  src/maps/tee-review-and-submit.map.ts
  src/qa-certification-workspace/cert-event-review-and-submit.repository.ts
  src/qa-certification-workspace/cert-event-review-and-submit.service.spec.ts
  src/qa-certification-workspace/cert-event-review-and-submit.service.ts
  src/qa-certification-workspace/qa-certification.controller.spec.ts
  src/qa-certification-workspace/qa-certification.controller.ts
  src/qa-certification-workspace/qa-certification.module.ts
  src/qa-certification-workspace/tee-review-and-submit.repository copy.ts
  src/qa-certification-workspace/tee-review-and-submit.service.spec.ts
  src/qa-certification-workspace/tee-review-and-submit.service.ts
  src/qa-certification-workspace/test-summary-review-and-submit.repository.ts
  src/qa-certification-workspace/test-summary-review-and-submit.service.spec.ts
  src/qa-certification-workspace/test-summary-review-and-submit.service.ts
  src/review-and-submit/review-and-submit-test-summary.controller.spec.ts
  src/review-and-submit/review-and-submit-test-summary.repository.ts
  src/review-and-submit/review-and-submit.controller.ts
  src/review-and-submit/review-and-submit.module.ts
  src/routes.ts
  src/test-summary-workspace/test-summary.controller.spec.ts
Labels: Tech Team

#379 Feature: componentID checks
  src/cycle-time-injection-workspace/cycle-time-injection-workspace-checks.service.spec.ts
  src/cycle-time-injection-workspace/cycle-time-injection-workspace-checks.service.ts
  src/cycle-time-injection-workspace/cycle-time-injection-workspace.module.ts
  src/dto/app-e-heat-input-from-gas.dto.ts
  src/dto/cycle-time-injection.dto.ts
  src/dto/test-summary.dto.ts
  src/qa-certification-workspace/qa-certification-checks.service.ts
  src/test-summary-workspace/test-summary-checks.service.spec.ts
  src/test-summary-workspace/test-summary-checks.service.ts
Labels: Emissioners

#380 fix: componentID check update
  src/dto/test-summary.dto.ts
Labels: Emissioners

#383 Feature/4695 4696 pgvp 12 13 checks
  src/app.module.ts
  src/entities/gas-component-code.entity.ts
  src/gas-component-code/gas-component-code.module.ts
  src/gas-component-code/gas-component-code.repository.ts
  src/protocol-gas-workspace/protocol-gas-checks.service.ts
  src/protocol-gas-workspace/protocol-gas.controller.ts
Labels: Emissioners

#385 fix pgvp dto validation bug
  src/dto/protocol-gas.dto.ts
  src/protocol-gas-workspace/protocol-gas.controller.ts
Labels: Emissioners

#388 4649 - QA Checks for Dups - Fix Bugs and Add Unit Tests
  src/app-e-heat-input-from-gas-workspace/app-e-heat-input-from-gas-checks.service.spec.ts
  src/app-e-heat-input-from-oil-workspace/app-e-heat-input-from-oil-checks.service.spec.ts
  src/cycle-time-injection-workspace/cycle-time-injection-workspace-checks.service.spec.ts
  src/test-summary-workspace/test-summary-checks.service.ts
Labels: Emissioners

#389 feature/Refactoring
  src/dto/cert-event-review-and-submit.dto.ts
  src/dto/review-and-submit-test-summary.dto.ts
  src/dto/tee-review-and-submit.dto.ts
  src/entities/workspace/cert-event-review-and-submit.entity.ts
  src/entities/workspace/tee-review-and-submit.entity.ts
  src/entities/workspace/test-summary-review-and-submit.entity.ts
  src/maps/cert-event-review-and-submit.map.ts
  src/maps/review-and-submit-test-summary.map.ts
  src/maps/tee-review-and-submit.map.ts
Labels: Tech Team

#390 🐛 Bug-Fix: Duplicate Check Messages and fix failing unit tests
  src/app-e-correlation-test-run-workspace/app-e-correlation-test-run-workspace.controller.spec.ts
  src/app-e-correlation-test-run-workspace/app-e-correlation-test-run-workspace.module.ts
  src/app-e-correlation-test-run-workspace/app-e-correlation-test-run-workspace.repository.ts
  src/app-e-correlation-test-summary-workspace/app-e-correlation-test-summary-workspace.controller.spec.ts
  src/app-e-heat-input-from-gas-workspace/app-e-heat-input-from-gas-checks.service.spec.ts
  src/app-e-heat-input-from-gas-workspace/app-e-heat-input-from-gas-checks.service.ts
  src/app-e-heat-input-from-gas-workspace/app-e-heat-input-from-gas-workspace.controller.spec.ts
  src/app-e-heat-input-from-gas-workspace/app-e-heat-input-from-gas-workspace.controller.ts
  src/app-e-heat-input-from-gas-workspace/app-e-heat-input-from-gas-workspace.module.ts
  src/app-e-heat-input-from-gas-workspace/app-e-heat-input-from-gas-workspace.repository.ts
  src/app-e-heat-input-from-oil-workspace/app-e-heat-input-from-oil-checks.service.spec.ts
  src/app-e-heat-input-from-oil-workspace/app-e-heat-input-from-oil-checks.service.ts
  src/app-e-heat-input-from-oil-workspace/app-e-heat-input-from-oil.controller.spec.ts
  src/app-e-heat-input-from-oil-workspace/app-e-heat-input-from-oil.controller.ts
  src/app-e-heat-input-from-oil-workspace/app-e-heat-input-from-oil.module.ts
  src/app-e-heat-input-from-oil-workspace/app-e-heat-input-from-oil.repository.ts
  src/cycle-time-injection-workspace/cycle-time-injection-checks.service.ts
  src/cycle-time-injection-workspace/cycle-time-injection-workspace-checks.service.spec.ts
  src/cycle-time-injection-workspace/cycle-time-injection-workspace-checks.service.ts
  src/cycle-time-injection-workspace/cycle-time-injection-workspace.controller.spec.ts
  src/cycle-time-injection-workspace/cycle-time-injection-workspace.repository.ts
  src/cycle-time-summary-workspace/cycle-time-summary-workspace.repository.ts
  src/protocol-gas-workspace/protocol-gas-checks.service.spec.ts
  src/protocol-gas-workspace/protocol-gas.controller.spec.ts
  src/qa-certification-workspace/qa-certification-checks.service.spec.ts
  src/rata-run-workspace/rata-run-checks.service.spec.ts
  src/test-summary-workspace/test-summary-checks.service.ts
Labels: Emissioners
